link_MyAccount= "xpath://span[@class='hidden-xs hidden-sm hidden-md'and text()='My Account']"
link_Register="//a[@href='http://tutorialsninja.com/demo/index.php?route=account/register']"
#firstName="#input-firstname"
firstName="//input[@id='input-firstname']"
#lastName="id:#input-lastname"
lastName="//input[@id='input-lastname']"
email="//input[@id='input-email']"
telephone="//input[@id='input-telephone']"
password="//input[@id='input-password']"
confirm="//input[@id='input-confirm']"
btn_continue="//input[@value='Continue']"